sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
script:
  - xvfb-run npm test
deploy:
  # CDN Latest
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_EVTJS_BUCKET
    local_dir: dist
    upload-dir: js/evrythng/latest
    skip_cleanup: true
    on:
      tags: true
  # CDN Versioned
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_EVTJS_BUCKET
    local_dir: dist
    upload-dir: js/evrythng/$TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
  # NPM
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: next
    on:
      tags: true